apiVersion: v1
kind: Service
metadata:
  labels:
    app: post-processor
  name: post-processor
spec:
  type: LoadBalancer
  ports:
  - name: "3003"
    port: 3003
    targetPort: 3000
    nodePort: 30005
  selector:
    app: post-processor
