---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  labels:
    name: kafka
spec:
  ports:
  - port: 9094
    name: kafka-port
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
    id: "2"
  type: LoadBalancer