---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-1
  labels:
    name: kafka
spec:
  ports:
  - port: 9093
    name: kafka-port
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
    id: "1"
  type: LoadBalancer