---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-broker-0
spec:
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-service"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: "data-retrieval-service:5:3,model-execution-service:5:3,user-management-service:5:3,post-processing-service:5:3,session-management-service:5:3,api-gateway-service:1:3,front-end-data-retrieval-service:5:3"