node {
    stage("Git clone") {
        git branch: 'master-data-processor', url: 'https://github.com/airavata-courses/HogwartsRejects.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t gkiran292/data-processor /var/lib/jenkins/workspace/ModellingService/PyNexRad/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u gkiran292 -p ${DockerPassword}"
        }
        sh "docker push gkiran292/data-processor"
    }
    
    stage('Redeploy Kubernetes') {
          sh '''

          ssh -i ~/hogwarts.pem ubuntu@149.165.171.174  " rm -rf ~/HogwartsRejects &&
          git clone --single-branch --branch master-data-processor https://github.com/airavata-courses/HogwartsRejects.git &&
          cd ~/HogwartsRejects/PyNexRad &&

          kubectl delete deployment data-processor &&
          kubectl apply -f ."

          '''
     }
}
