node {
    stage("Git clone") {
        git branch: 'feature-python-modeler', url: 'https://github.com/airavata-courses/HogwartsRejects.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t gkiran292/data-processor /var/lib/jenkins/workspace/ModellingService/PyNexRad/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u gkiran292 -p ${DockerPassword}"
        }
        sh "docker push gkiran292/data-processor"
    }

    stage('SSH to Kubernetes master') {
         sh '''
         ssh -tt -o StrictHostKeyChecking=no -i ~/hogwarts.pem ubuntu@149.165.171.174
         git clone --single-branch --branch develop https://github.com/airavata-courses/HogwartsRejects.git &&
         cd HogwartsRejects/k8s/data-processor
         kubectl delete service data-processor &&
         kubectl delete deployment data-processor &&
         kubectl apply -f ."
         rm -rf ~/HogwartsRejects
         '''
     }
}
