node {
    stage("Git clone") {
        git branch: 'feature-api-gw', url: 'https://github.com/airavata-courses/HogwartsRejects.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t gkiran292/api-gateway /var/lib/jenkins/workspace/APIGateway/APIGateway/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u gkiran292 -p ${DockerPassword}"
        }
        sh "docker push gkiran292/api-gateway"
    }
}
