apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-retriever
  name: data-retriever
spec:
  ports:
  - name: "3002"
    port: 3002
    targetPort: 3000
    nodePort: 30001
  selector:
    app: data-retriever