node {
    stage("Git clone") {
        git branch: 'master-climate-data-retrieval', url: 'https://github.com/airavata-courses/HogwartsRejects.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t gkiran292/data-retriever /var/lib/jenkins/workspace/DataRetriever/climate-app/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u gkiran292 -p ${DockerPassword}"
        }
        sh "docker push gkiran292/data-retriever"
    }
    
    stage('Redeploy Kubernetes') {
          sh '''

          ssh -i ~/hogwarts.pem ubuntu@149.165.171.174  " rm -rf ~/HogwartsRejects &&
          git clone --single-branch --branch develop https://github.com/airavata-courses/HogwartsRejects.git &&
          cd ~/HogwartsRejects/k8s/data-retriever &&

          kubectl delete service data-retriever &&
          kubectl delete deployment data-retriever &&
          kubectl apply -f ."

          '''
     }
}
