apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090
    nodePort: 30002
  selector:
    app: api-gateway