apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-management
  name: user-management
spec:
  type: LoadBalancer
  ports:
  - name: "3004"
    port: 3004
    targetPort: 3000
    nodePort: 30003
  selector:
    app: user-management
