node {
    stage("Git clone") {
        git branch: 'master-UI', url: 'https://github.com/airavata-courses/HogwartsRejects.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t gkiran292/ads-ui /var/lib/jenkins/workspace/UI/UI/hogwarts-rejects/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u gkiran292 -p ${DockerPassword}"
        }
        sh "docker push gkiran292/ads-ui"
    }
    
     stage('Redeploy Kubernetes') {
          sh '''

          ssh -i ~/hogwarts.pem ubuntu@149.165.171.174  " rm -rf ~/HogwartsRejects &&
          git clone --single-branch --branch master-UI https://github.com/airavata-courses/HogwartsRejects.git &&
          cd ~/HogwartsRejects/UI/hogwarts-rejects &&

          kubectl delete service ads-ui &&
          kubectl delete deployment ui &&
          kubectl apply -f ."

          '''
      }
}

