node {
    stage("Git clone") {
        git branch: 'master-post-processor', url: 'https://github.com/airavata-courses/HogwartsRejects.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t gkiran292/post-processor /var/lib/jenkins/workspace/PostProcessor/PostProcessor/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u gkiran292 -p ${DockerPassword}"
        }
        sh "docker push gkiran292/post-processor"
    }
    
     stage('Redeploy Kubernetes') {
          sh '''

          ssh -i ~/hogwarts.pem ubuntu@149.165.171.174  " rm -rf ~/HogwartsRejects &&
          git clone --single-branch --branch develop https://github.com/airavata-courses/HogwartsRejects.git &&
          cd ~/HogwartsRejects/k8s/post-processor &&

          kubectl delete service post-processor &&
          kubectl delete deployment post-processor &&
          kubectl apply -f ."

          '''
      }
}
