node {
    stage("Git clone") {
        git branch: 'feature/sessionmanagement', url: 'https://github.com/airavata-courses/HogwartsRejects.git'
    }

    stage("Gradle build") {
        def gradleHome = tool name:"Gradle51", type: "gradle"
        sh "${gradleHome}/bin/gradle build"
    }

    stage("Build Docker Image") {
         sh "docker build -t gkiran292/session-management /var/lib/jenkins/workspace/SessionManagement/SessionManagement/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u gkiran292 -p ${DockerPassword}"
        }
        sh "docker push vivekshresta/session-management"
    }
    
    stage('Kubernetes deploy') {
         sh '''
         ssh -o StrictHostKeyChecking=no -i ~/hogwarts.pem ubuntu@149.165.171.174
         rm -rf ~/HogwartsRejects
         git clone --single-branch --branch develop https://github.com/airavata-courses/HogwartsRejects.git &&
         cd HogwartsRejects/k8s/session-management
         kubectl delete service session-management &&
         kubectl delete deployment session-management &&
         kubectl apply -f ."
         rm -rf ~/HogwartsRejects
         '''
     }
}
