node {
    stage("Git clone") {
        git branch: 'feature/login', url: 'https://github.com/airavata-courses/HogwartsRejects.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t gkiran292/user-management /var/lib/jenkins/workspace/UserManagement/UserManagement/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u gkiran292 -p ${DockerPassword}"
        }
        sh "docker push gkiran292/user-management"
    }

    stage('SSH to Kubernetes master') {
         sh '''
         rm -rf ~/HogwartsRejects
         ssh -o StrictHostKeyChecking=no -i ~/hogwarts.pem ubuntu@149.165.171.98
         git clone --single-branch --branch develop https://github.com/airavata-courses/HogwartsRejects.git &&
         cd HogwartsRejects/k8s/user-management

         kubectl delete service user-management &&
         kubectl delete deployment user-management &&
         kubectl apply -f ."
         rm -rf ~/HogwartsRejects
         '''
     }
}
