node {
    stage("Git clone") {
        git branch: 'master-user-management', url: 'https://github.com/airavata-courses/HogwartsRejects.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t gkiran292/user-management /var/lib/jenkins/workspace/UserManagement/UserManagement/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u gkiran292 -p ${DockerPassword}"
        }
        sh "docker push gkiran292/user-management"
    }

    stage('Redeploy Kubernetes') {
         sh '''

         ssh -i ~/hogwarts.pem ubuntu@149.165.171.174  " rm -rf ~/HogwartsRejects &&
         git clone --single-branch --branch master-user-management https://github.com/airavata-courses/HogwartsRejects.git &&
         cd ~/HogwartsRejects &&

         kubectl delete service user-management &&
         kubectl delete deployment user-management &&
         kubectl apply -f ."

         '''
     }
}
