pipeline {
    stages {
        stage("Git clone") {
            step {
                git branch: 'feature/login', url: 'https://github.com/airavata-courses/HogwartsRejects.git'
            }
        }

        stage("Gradle clean build") {
            step {
                def gradleHome = tool name:"Gradle51", type: "gradle"
                sh "${gradleHome}/bin/gradle build"
            }
        }

        stage("Build Docker Image") {
            step {
                sh "docker build -t vivekshresta/userapp /var/lib/jenkins/workspace/UserManagement/UserManagement/"
            }
        }

        stage("Docker image push") {
            step {
                withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
                    sh "docker login -u vivekshresta -p ${DockerPassword}"
                }
                sh "docker push vivekshresta/userapp"
            }
        }
    }
}