apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: session-management
  name: session-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-management
  template:
    metadata:
      labels:
        app: session-management
    spec:
      containers:
      - image: docker.io/gkiran292/session-management
        name: session-management
        ports:
        - containerPort: 3000
      restartPolicy: Always
