apiVersion: v1
kind: Service
metadata:
  labels:
    app: session-management
  name: session-management
spec:
  type: LoadBalancer
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3000
    nodePort: 30004
  selector:
    app: session-management
